# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66727067885157695055990b4a20eae763babb5cd565255dd4681fdceb3f174b424485063577d22c9fe6d46319aa5fd8e8371ea205a733d0387db5d3fbe34596

test:
  secret_key_base: 98efb37cc60b25fedb9679fcc412a1cd7d1b473b1b4e05811b5408c0f298065f6a9ab95c9b6ac0af27ff274f690ee2b10194a2e21a4c3b9b9879f41ad1f35136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
